#服务配置
server:
  #address: 127.0.0.1
  port: 8801
  tomcat:
    compression: on
---
## ???不知何用
management:
  address: 127.0.0.1
  port: 9001
---
###spring配置
spring:
  ###APPLICATION SETTINGS
  main:
    show-banner: false
  ###数据库连接字符串
  datasource:
    url: jdbc:mysql://jra/jra?useUnicode=true&characterEncoding=UTF-8
    username: mintcode
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
